workflow:
  rules:
    - when: always

stages:
  - test

combined-coverage-sonarqube-check:
  stage: test
  when: manual
  rules:
    - when: always
  allow_failure: true
  script:
    - make sonar_check

