[package]
name = "kernel"
version = "0.3.0"
edition = "2024"

[dependencies]
bootloader = "0.9"
x86_64 = "0.14"

[[bin]]
name = "x86_64-r2"
path = "src/main.rs"
test = false
doctest = false
bench = false
