const MULTIBOOT_HEADER: u32 = 1;

const MULTIBOOT_SEARCH: u32 = 32768;

const MULTIBOOT2_HEADER_MAGIC: u32 = 0xe85250d6;
const MULTIBOOT2_BOOTLOADER_MAGIC: u32 = 0x36d76289;

const MULTIBOOT_MOD_ALIGN: u32 = 0x00001000;
const MULTIBOOT_INFO_ALIGN: u32 = 0x00000008;
const MULTIBOOT_TAG_ALIGN: u32 = 8;
const MULTIBOOT_HEADER_ALIGN: u8 = 8;

enum MULTIBOOT_TAG_TYPE {
    MULTIBOOT_TAG_TYPE_END              = 0,
    MULTIBOOT_TAG_TYPE_CMDLINE          = 1,
    MULTIBOOT_TAG_TYPE_BOOT_LOADER_NAME = 2,
    MULTIBOOT_TAG_TYPE_MODULE           = 3,
    MULTIBOOT_TAG_TYPE_BASIC_MEMINFO    = 4,
    MULTIBOOT_TAG_TYPE_BOOTDEV          = 5,
    MULTIBOOT_TAG_TYPE_MMAP             = 6,
    MULTIBOOT_TAG_TYPE_VBE              = 7,
    MULTIBOOT_TAG_TYPE_FRAMEBUFFER      = 8,
    MULTIBOOT_TAG_TYPE_ELF_SECTIONS     = 9,
    MULTIBOOT_TAG_TYPE_APM              = 10,
    MULTIBOOT_TAG_TYPE_EFI32            = 11,
    MULTIBOOT_TAG_TYPE_EFI64            = 12,
    MULTIBOOT_TAG_TYPE_SMBIOS           = 13,
    MULTIBOOT_TAG_TYPE_ACPI_OLD         = 14,
    MULTIBOOT_TAG_TYPE_ACPI_NEW         = 15,
    MULTIBOOT_TAG_TYPE_NETWORK          = 16,
    MULTIBOOT_TAG_TYPE_EFI_MMAP         = 17,
    MULTIBOOT_TAG_TYPE_EFI_BS           = 18,
    MULTIBOOT_TAG_TYPE_EFI32_IH         = 19,
    MULTIBOOT_TAG_TYPE_EFI64_IH         = 20,
    MULTIBOOT_TAG_TYPE_LOAD_BASE_ADDR   = 21,
}

enum MULTIBOOT_HEADER_TAG {
    MULTIBOOT_HEADER_TAG_END  = 0,
    MULTIBOOT_HEADER_TAG_INFORMATION_REQUEST = 1,
    MULTIBOOT_HEADER_TAG_ADDRESS = 2,
    MULTIBOOT_HEADER_TAG_ENTRY_ADDRESS = 3,
    MULTIBOOT_HEADER_TAG_CONSOLE_FLAGS = 4,
    MULTIBOOT_HEADER_TAG_FRAMEBUFFER = 5,
    MULTIBOOT_HEADER_TAG_MODULE_ALIGN = 6,
    MULTIBOOT_HEADER_TAG_EFI_BS       = 7,
    MULTIBOOT_HEADER_TAG_ENTRY_ADDRESS_EFI32 = 8,
    MULTIBOOT_HEADER_TAG_ENTRY_ADDRESS_EFI64 = 9,
    MULTIBOOT_HEADER_TAG_RELOCATABLE = 10,
}

enum MULTIBOOT_MEMORY {
    MULTIBOOT_MEMORY_AVAILABLE              = 1,
    MULTIBOOT_MEMORY_RESERVED               = 2,
    MULTIBOOT_MEMORY_ACPI_RECLAIMABLE       = 3,
    MULTIBOOT_MEMORY_NVS                    = 4,
    MULTIBOOT_MEMORY_BADRAM                 = 5,
}

const MULTIBOOT_ARCHITECTURE_I386: u8 = 0;
const MULTIBOOT_ARCHITECTURE_MIPS32: u8 =  4;
const MULTIBOOT_HEADER_TAG_OPTIONAL: u8 = 1;

enum MULTIBOOT_LOAD_PREFERENCE {
    MULTIBOOT_LOAD_PREFERENCE_NONE = 0,
    MULTIBOOT_LOAD_PREFERENCE_LOW  = 1,
    MULTIBOOT_LOAD_PREFERENCE_HIGH = 2,
}

const MULTIBOOT_CONSOLE_FLAGS_CONSOLE_REQUIRED: u8 = 1;
const MULTIBOOT_CONSOLE_FLAGS_EGA_TEXT_SUPPORTED: u8 = 2;

